provider "aws" {
  region = "eu-central-1"
}

data "aws_caller_identity" "current" {}

module "s3_backend" {
  source      = "./modules/s3-backend"
  bucket_name = "terraform-demo-bucket-${data.aws_caller_identity.current.account_id}"
}

module "vpc" {
  source             = "./modules/vpc"
  vpc_cidr_block     = "10.0.0.0/16"
  public_subnets     = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  private_subnets    = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
  availability_zones = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
  vpc_name           = "terraform-demo-vpc"
  cluster_name       = "eks-cluster-demo" # для тегування підмереж під Kubernetes LoadBalancer
}

module "ecr" {
  source       = "./modules/ecr"
  ecr_name     = "terraform-demo-ecr"
  scan_on_push = true
}

module "eks" {
  source       = "./modules/eks"
  region       = "eu-central-1"
  cluster_name = "eks-cluster-demo" # Назва кластера
  # Control plane бачить усі підмережі; ноди живуть лише в приватних (вихід через NAT gateway).
  subnet_ids      = concat(module.vpc.public_subnets, module.vpc.private_subnets)
  node_subnet_ids = module.vpc.private_subnets
  instance_type   = "t3.small" # Тип інстансів (t3.micro дає лише 4 поди на ноду — замало для CSI + Jenkins)
  desired_size    = 3          # Бажана кількість нодів
  max_size        = 3          # Максимальна кількість нодів
  min_size        = 1          # Мінімальна кількість нодів
}

data "aws_eks_cluster_auth" "eks" {
  name = module.eks.eks_cluster_name
}

provider "helm" {
  kubernetes {
    host                   = module.eks.eks_cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.eks_cluster_certificate_authority)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", module.eks.eks_cluster_name, "--region", "eu-central-1"]
    }
  }
}

provider "kubernetes" {
  host                   = module.eks.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.eks_cluster_certificate_authority)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.eks.eks_cluster_name, "--region", "eu-central-1"]
  }
}

module "jenkins" {
  source             = "./modules/jenkins"
  cluster_name       = module.eks.eks_cluster_name
  oidc_provider_arn  = module.eks.oidc_provider_arn
  oidc_provider_url  = module.eks.oidc_provider_url
  ecr_repository_arn = module.ecr.ecr_repository_arn
  github_username    = var.github_username
  github_pat         = var.github_pat

  providers = {
    helm       = helm
    kubernetes = kubernetes
  }
}

module "argo_cd" {
  source        = "./modules/argo-cd"
  namespace     = "argocd"
  chart_version = "5.46.4"

  providers = {
    helm = helm
  }

  depends_on = [module.eks]
}


# Kubernetes Secret that makes the RDS endpoint and password available to the
# Django Helm chart without storing sensitive values in Git.  The Secret name
# matches the `rdsSecretName` value in charts/django-app/values.yaml.
resource "kubernetes_secret" "django_rds" {
  metadata {
    name      = "django-app-rds"
    namespace = "default"
  }

  data = {
    POSTGRES_HOST     = module.rds.endpoint
    POSTGRES_PASSWORD = module.rds.password
  }

  depends_on = [module.eks]
}

module "monitoring" {
  source = "./modules/monitoring"

  grafana_admin_password = var.grafana_admin_password

  providers = {
    helm = helm
  }

  depends_on = [module.eks]
}

module "rds" {
  source = "./modules/rds"

  name       = "terraform-demo-db"
  use_aurora = false # Free Tier: standard RDS only (Aurora is NOT Free Tier eligible)

  # --- Aurora-only (used when use_aurora = true) ---
  engine_cluster                = "aurora-postgresql"
  engine_version_cluster        = "15.3"
  parameter_group_family_aurora = "aurora-postgresql15"
  aurora_replica_count          = 1

  # --- Standard RDS-only ---
  engine                     = "postgres"
  engine_version             = "17.5"
  parameter_group_family_rds = "postgres17"

  # Common
  instance_class    = "db.t3.micro" # Free Tier eligible
  allocated_storage = 20            # Free Tier allows up to 20 GB
  db_name           = "terraform_demo"
  username          = "postgres"
  # No password here: it is auto-generated by the module (like the Jenkins admin
  # password). Override with TF_VAR_rds_password if you need a fixed value.
  password                = var.rds_password
  subnet_private_ids      = module.vpc.private_subnets
  subnet_public_ids       = module.vpc.public_subnets
  publicly_accessible     = false # keep the DB private; flip to true only if you must
  vpc_id                  = module.vpc.vpc_id
  multi_az                = false # Multi-AZ is NOT Free Tier eligible
  backup_retention_period = 0     # Free Tier plan forbids automated backups; use >0 on a paid plan
  skip_final_snapshot     = true  # convenient for the demo/teardown

  parameters = {
    max_connections            = "200"
    log_min_duration_statement = "500"
  }

  tags = {
    Environment = "dev"
    Project     = "terraform-demo"
  }
}
