controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - github
    - job-dsl

  JCasC:
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: pilotocheg
                      password: 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
                      description: GitHub PAT
      seed-job: |
        jobs:
          - script: >
              job('seed-job') {
                description('Job to generate pipeline for Django project')
                scm {
                  git {
                    remote {
                      url('https://github.com/pilotocheg/goit-devops-django-project.git')
                      credentials('github-token')
                    }
                    branches('*/main')
                  }
                }
                steps {
                  dsl {
                    text('''
                      pipelineJob("goit-django-docker") {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("https://github.com/pilotocheg/goit-devops-django-project.git")
                                  credentials("github-token")
                                }
                                branches("*/main")
                              }
                            }
                          }
                        }
                      }
                    ''')
                  }
                }
              }

serviceAccount:
  create: true
  name: jenkins-sa
  annotations:
    eks.amazonaws.com/role-arn: ${kaniko_role_arn}

persistence:
  enabled: true
  storageClass: "ebs-sc"
  size: 10Gi
