{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            {{- if .Values.rdsSecretName }}
            - secretRef:
                name: {{ .Values.rdsSecretName }}
            {{- else }}
            - secretRef:
                name: {{ .Release.Name }}-secret
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.config.POSTGRES_USER }}
                - -d
                - {{ .Values.config.POSTGRES_DB }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.config.POSTGRES_USER }}
                - -d
                - {{ .Values.config.POSTGRES_DB }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: {{ .Values.config.POSTGRES_PORT }}
      targetPort: 5432
{{- end }}
