{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - port: {{ .Values.config.POSTGRES_PORT }}
      targetPort: 5432
{{- end }}
