applications:
  - name: django-app
    project: default
    source:
      repoURL: https://github.com/pilotocheg/goit-devops-hw.git
      path: charts/django-app
      targetRevision: lesson-8-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
